//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crawler.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crawler.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;&lt;title&gt;
        ///	╨а╨╡╨╖╤Г╨╗╤М╤В╨░╤В╤Л ╨┐╨╛╨╕╤Б╨║╨░
        ///&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;ru&quot; /&gt;
        ///&lt;meta name=&quot;copyright&quot; content=&quot;copyright ┬й2010&quot; /&gt;
        ///
        ///&lt;link rel=&quot;shortcut icon&quot; href=&quot;http://rabota.ua/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///&lt;link rel=&quot;search&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RabotaUaPage1 {
            get {
                return ResourceManager.GetString("RabotaUaPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head id=&quot;ctl00_Head1&quot;&gt;&lt;title&gt;
        ///	╨а╨░╨▒╨╛╤В╨░: Snr Java Software Engineer ╨▓ ╨Ъ╨╕╨╡╨▓╨╡, ╨▓╨░╨║╨░╨╜╤Б╨╕╤П Snr Java Software Engineer ╨▓ EPAM / ╨н╨┐╨░╨╝ / ╨Д╨┐╨░╨╝, ╨╕╤Й╤Г ╤А╨░╨▒╨╛╤В╤Г ╨Ъ╨╕╨╡╨▓, ╤В╤А╤Г╨┤╨╛╤Г╤Б╤В╤А╨╛╨╣╤Б╤В╨▓╨╛
        ///&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeniorJavaWithTdd {
            get {
                return ResourceManager.GetString("SeniorJavaWithTdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;vacancyitem proffesional_vacancyitem&quot;&gt;
        ///					&lt;div class=&quot;first&quot;&gt;
        ///						&lt;a class=&quot;companyLogo&quot; href=&quot;/company1074&quot;&gt;&lt;img alt=&quot;Р&apos;С_Рч Р_Р°РєР°Р_С_РёРё РєР_Р_РїР°Р_РёРё EPAM / Р-РїР°Р_ / Р&quot;РїР°Р_&quot; src=&quot;/Data/cImg/job@epam.com_20080305122308.gif&quot; /&gt;&lt;/a&gt;
        ///						&lt;a class=&quot;vacancyName jqKeywordHighlight&quot; href=&quot;/company1074/vacancy4516336&quot;&gt;Snr Java Software Engineer&lt;/a&gt;
        ///						&lt;div class=&quot;companyName&quot;&gt;&lt;a title=&quot;Р&apos;С_Рч Р_Р°РєР°Р_С_РёРё РєР_Р_РїР°Р_РёРё EPAM / Р-РїР°Р_ / Р&quot;РїР°Р_&quot; href=&quot;/company1074/all_v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleDivResultPage {
            get {
                return ResourceManager.GetString("SingleDivResultPage", resourceCulture);
            }
        }
    }
}
