<?xml version="1.0" encoding="utf-8"?><Database Name="cqrstestdb" Class="DataModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=cqrstestdb;Integrated Security=True" SettingsObjectName="Ivanov.Build.Server.Cqrs.Properties.Settings" SettingsPropertyName="cqrstestdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Jobs" Member="Jobs">
    <Type Name="Job">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastRun" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobConfigurations" Member="JobConfigurations">
    <Type Name="JobConfiguration">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BatchName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="JobName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>